### ISSUE TITLE
ModuleNotFoundError: No module named 'models.text_encoder'

### ISSUE THREAD

**Issue by ashmalvayani** [algoprog/Quin#12]
I have downloaded **NLI model** weights and **Densed Encoder FC** in the folder model/weights folder.
After extracting the relevant folder in the model/weights directory, it looks like this:
![image](https://github.com/algoprog/Quin/assets/56957881/2f7ba68b-a750-4d95-bbf8-39fe1a97776e)

I also had to modify the following line otherwise it would not detect my model:
self.text_embedding_model = SentenceTransformer('{}/encoder/qrbert-factcheck'.format(models_path), device=device)

Now, I am getting the following error:
![image](https://github.com/algoprog/Quin/assets/56957881/b2081eaa-757b-427b-9913-614790f7e17e)

Can you help resolve this error and show exactly how to configure your codebase?

**Comment by hedarko20** [comment]
You need to put the contents of the BERT folder into the encoder.
